### ISSUE TITLE
Vagrant up fails if no ubuntu-16.04-amd64 box exists

### ISSUE THREAD

**Issue by ghost** [rgl/gitlab-vagrant#1]
*vagrant up* fails if the box **ubuntu-16.04-amd64** doesn't exist yet on the local machine.

**Comment by rgl** [comment]
Indeed. Install it from https://github.com/rgl/Ubuntu vagrant. I'll update the Readme.

**Comment by rgl** [comment]
Indeed. Install it from https://github.com/rgl/ubuntu-vagrant. I'll update the Readme.

**Comment by ghost** [comment]
I tried it with *kaorimatz/ubuntu-16.04-amd64*, worked fine.

**Comment by rgl** [comment]
Nice to known that base image works too. Anyways, I've update the readme. Thanks for the report.
